// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETmNQToV-7_yOea0KYuIFbBBf0NenubU',
    appId: '1:480731842391:web:1ea0e6005aea4e75692012',
    messagingSenderId: '480731842391',
    projectId: 'ihomey-36b9d',
    authDomain: 'ihomey-36b9d.firebaseapp.com',
    storageBucket: 'ihomey-36b9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKNj-aEj8nHselhZWdPFt3HHq_Ahuz2GU',
    appId: '1:480731842391:android:f58a112bf4d2e9d4692012',
    messagingSenderId: '480731842391',
    projectId: 'ihomey-36b9d',
    storageBucket: 'ihomey-36b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBzeh6YJRJR9uWhLZsXT3qGi5OisEsdc',
    appId: '1:480731842391:ios:00fc7c784da02f33692012',
    messagingSenderId: '480731842391',
    projectId: 'ihomey-36b9d',
    storageBucket: 'ihomey-36b9d.firebasestorage.app',
    iosBundleId: 'com.example.ihomey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBzeh6YJRJR9uWhLZsXT3qGi5OisEsdc',
    appId: '1:480731842391:ios:00fc7c784da02f33692012',
    messagingSenderId: '480731842391',
    projectId: 'ihomey-36b9d',
    storageBucket: 'ihomey-36b9d.firebasestorage.app',
    iosBundleId: 'com.example.ihomey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBETmNQToV-7_yOea0KYuIFbBBf0NenubU',
    appId: '1:480731842391:web:be28a5f30328cd50692012',
    messagingSenderId: '480731842391',
    projectId: 'ihomey-36b9d',
    authDomain: 'ihomey-36b9d.firebaseapp.com',
    storageBucket: 'ihomey-36b9d.firebasestorage.app',
  );

}